version: "3"

services:
  client:
    entrypoint: npx serve -s build/ -l 3000
    environment:
      NODE_ENV: production
    build:
      args:
        NODE_ENV: production
        REACT_APP_API_URL: https://ayesaac-back.box.noerls.com
